FROM python:3.10-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir google-genai tenacity pydantic requests httpx google-auth websockets anyio annotated-types typing-inspection charset-normalizer urllib3 cffi pyasn1 pycparser cryptography
ENTRYPOINT ["python3"]
