name: Research Status
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Unique Run ID'
        required: true
jobs:
  status:
    runs-on: [self-hosted, linux, wsl]
    steps:
      - uses: actions/checkout@v4
      - name: Get Research Run Status
        run: scripts/wsl status --run-id "${{ github.event.inputs.run_id }}"
